<?php

namespace App\Http\Controllers\v1\app\reports\organization;

use ZipArchive;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\AddressTrait;
use App\Traits\PdfGeneratorTrait;
use Illuminate\Support\Facades\Log;

class OrganizationReportsController extends Controller
{
    //


    use PdfGeneratorTrait, AddressTrait;

    public function generateReport(Request $request)
    {

        $lang = $request->language ?? 'en';

        $mpdf = $this->generatePdf();
        $this->setWatermark($mpdf);

        $data = $this->loadData($lang);

        // Footer HTML
        $footerHtml = '
        <div style="width:100%; text-align:center; font-size:10pt; color:#555; border-top:1px solid #999; padding-top:5px;">
            Date: _____________ <br>
            Generated by: Ahmad Ali
        </div>
    ';
        $this->setFooter($mpdf, $footerHtml);

        $this->pdfFilePart($mpdf, "reports.organization.{$lang}.cover", $data);

        $mpdf->AddPage('L');
        $this->setFooter($mpdf, '');

        $mpdf->SetProtection(['print']);

        // Save PDF to temp storage
        $fileName = "organization_report_{$lang}.pdf";
        $outputPath = storage_path("app/private/temp/");
        if (!is_dir($outputPath)) {
            mkdir($outputPath, 0755, true);
        }
        $filePath = $outputPath . $fileName;

        $mpdf->Output($filePath, 'I'); // Save to file

        // Return file and delete after send
        return response()->download($filePath)->deleteFileAfterSend(true);
    }


    protected function  coverData($locale = 'en')
    {
        $data = [
            'ngo_name' => 'ngo name',
        ];
        return $data;
    }
    protected function loadData($locale = 'en')
    {


        $data = [
            'ngo_name' => 'ngo name',
            'column' => [
                'Organization',
                'Country',
                'Projects',
                'Start Date',
                'End Date',
                'Total Budget',
                'Province',
                'Direct Beneficiaries',
                'Indirect Beneficiaries'
            ],
            'tableData' => [
                [
                    'organization_name' => 'Ahmad',
                    'related_country' => 'Afghanistan',
                    'total_budget' => '$100,000',
                    'project' => [
                        'project_name' => 'Project 1',
                        'start_date' => '2023-01-01',
                        'end_date' => '2023-12-31',
                        'provinces' => [
                            'name' =>  'kabul',
                            'direct_beneficiaries' => 500,
                            'indirect_beneficiaries' => 2000

                        ],


                    ],
                ],
                [
                    'organization_name' => 'Ahmad',
                    'related_country' => 'Afghanistan',
                    'total_budget' => '$100,000',
                    'project' => [
                        'project_name' => 'Project 1',
                        'start_date' => '2023-01-01',
                        'end_date' => '2023-12-31',
                        'provinces' => [
                            'name' =>  'kabul',
                            'direct_beneficiaries' => 500,
                            'indirect_beneficiaries' => 2000

                        ],


                    ],
                ],
                [
                    'organization_name' => 'Ahmad',
                    'related_country' => 'Afghanistan',
                    'total_budget' => '$100,000',
                    'project' => [
                        'project_name' => 'Project 1',
                        'start_date' => '2023-01-01',
                        'end_date' => '2023-12-31',
                        'provinces' => [
                            'name' =>  'kabul',
                            'direct_beneficiaries' => 500,
                            'indirect_beneficiaries' => 2000

                        ],


                    ],
                ],
            ],
        ];
        // $data = [
        //     'register_number' => $ngo->registration_no,
        //     'date_of_sign' => '................',
        //     'ngo_name' =>  $ngo->name,
        //     'abbr' => $ngo->abbr,
        //     'contact' => $ngo->contact,
        //     'address' => $ngo->area . ',' . $ngo->district . ',' . $ngo->province . ',' . $ngo->country,
        //     'director' => $director->name . " " . $director->last_name,
        //     'director_address' =>  $director->area . ',' . $director->district . ',' . $director->province . ',' . $director->country,
        //     'email' => $ngo->email,
        //     'establishment_date' => $ngo->date_of_establishment,
        //     'place_of_establishment' => $ngo->country,
        //     'ministry_economy_no' => $ngo->moe_registration_no,
        //     'general_objective' => $ngo->general_objective,
        //     'afganistan_objective' => $ngo->objective,
        //     'mission' => $ngo->mission,
        //     'vission' => $ngo->vision,
        //     'ird_director' => $irdDirector->name,
        // ];


        return $data;
    }
}
