<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <style>
        .coverpage {
            width: 210mm;
            height: 297mm;
            margin: 0 0;
            /* padding: 20mm; */
            box-sizing: border-box;
            /* page-break-after: always; */
            padding: 0;
        }

        .card {
            width: 100%;
            margin-bottom: 20mm;
        }

        /* @media print {
      .card {
        page-break-inside: avoid;
      }
    } */
        .info {
            width: 100%;
            align-items: center;
            /* border:1px solid red; */
            grid: auto;
        }

        img.islamic_logo {
            width: 80px;
            height: 80px;
            float: right;
            margin-top: 10px;
            margin-right: -10px
        }

        img.moph_logo {
            width: 85px;
            height: 80px;
            float: left;
            margin-top: 10px;
            margin-left: -10px;
        }

        div.mintext {
            /* position: ; */
            text-align: center;
            float: left;
            width: auto;
            margin: 0;
            padding-top: 30%;
            margin-left: auto;
            /* margin-top:10px; */
            font-size: 18px;
        }

        div.mintextKey {
            /* position: ; */
            text-align: center;
            float: left;
            width: auto;
            margin: 0;
            margin-top: 0px;
            margin-left: auto;
            /* margin-top:10px; */
            font-size: 0.9rem;
        }

        .maintext {
            width: 100%;
            text-align: center;
        }

        .title {
            float: left;
            margin-left: 40px;
            text-align: left;
        }

        .detail_value {
            float: right;
            text-align: center;
        }

        .contents {
            float: right;
            right: 0;
            padding-right: -40px;
            margin-left: 200px;
        }

        table.table {
            width: 95%;
            text-align: left;
            /* border: 2px solid black; */
            padding: 0;
            margin-left: auto;
            margin-right: auto;
            margin-top: 10px;
        }

        table.table tr td {
            border: 1px solid black;
            margin: 0;
            font-size: 1rem;
        }

        table.table tr th {
            border: 1px solid black;
            margin: 0;
            font-size: 1rem;
            text-align: left;
        }

        .bottomdiv {
            height: 30%;
            border: 1px solid black;
            width: 150%;
            padding: 0px;
            margin: 0px;
        }

        /* .setFooter {
            position: absolute;
            bottom: 0mm;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10pt;
        } */
        .setFooter {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            background-color: rgb(100, 165, 235);
            height: 22%;
            color: white;
            text-align: center;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 30px 80px;
            box-sizing: border-box;
            font-family: sans-serif;
            font-size: 10pt;
        }
    </style>

    <body style="margin:0; padding:0;">

        <div class="coverpage">

            <div class="card">

                <div class="info">

                    <img src="images/islamic.png" alt="img" class="islamic_logo" style="">
                    <img src="images/moph.png" alt="" class="moph_logo" style="">
                    <div class="mintext">
                        Islamic Emirate of Afghanistan
                        <br>
                        Ministry of Public Health
                        {{-- --}}
                        <br>
                        Directorate of international realtion and aid coordenation
                        <br>
                        <br>
                        <br>
                        <strong style="font-size:22px;">Report of new Project in kabul </strong>
                        <br>

                        <br>

                    </div>

                </div>

                <div class="maintext">
                    Date: _____________ <br>
                    Generated by: Ahmad Ali <br>
                </div>

            </div>

        </div>

    </body>

</html>
